'use client';
const number=value=>Number(value||0).toLocaleString();
const date=value=>value?new Date(value).toLocaleString():'—';
function ActivityRow({a}){return <tr><td><strong>{a.label}</strong><small>{a.status}</small></td><td>{date(a.last_activity)}</td><td>{number(a.opens)}</td><td>{number(a.wallets)}</td><td>{number(a.analyses)} / {number(a.extensions)}</td><td>{number(a.transactions)}</td><td>{number(a.credits_available)}</td><td>{number(a.credits_consumed)} / {number(a.credits_reserved)}</td><td>{number(a.completed)} / {number(a.pending)} / {number(a.paused)} / {number(a.failed)}</td><td>{date(a.expires_at)}</td><td>{a.last_error||'—'}</td></tr>}
export default function BetaUsageTables({usage}){
 if(!usage)return <p>Loading beta activity…</p>;
 const s=usage.summary||{};
 return <div className="beta-usage"><h3>Beta activity</h3><p>Refreshes every 15 seconds · {date(usage.updatedAt)}. Opens count successful explicit wallet access actions, including revisits and trade links. Automatic refreshes and history extensions do not count as opens. Tracking begins with this release.</p><div className="smart-metrics"><div><span>Activated testers</span><strong>{number(s.testers)} / 25</strong></div><div><span>Active · 24h</span><strong>{number(s.active24h)}</strong></div><div><span>Wallet opens</span><strong>{number(s.opens)}</strong></div><div><span>New transactions saved</span><strong>{number(s.newTransactions)}</strong></div><div><span>Credits consumed</span><strong>{number(s.creditsConsumed)}</strong></div><div><span>Pending / paused / failed</span><strong>{number(s.pending)} / {number(s.paused)} / {number(s.failed)}</strong></div></div>
 <div className="usage-table-scroll"><table className="usage-table"><caption>Activity by beta tester</caption><thead><tr><th>Tester / status</th><th>Last activity</th><th>Opens</th><th>Distinct wallets</th><th>Analyses / extensions</th><th>New transactions</th><th>Credits available</th><th>Used / reserved</th><th>Complete / pending / paused / failed</th><th>Expires</th><th>Last error</th></tr></thead><tbody>{usage.testers.map(a=><ActivityRow key={a.id} a={a}/>)}{usage.invitations.map((i,n)=><tr key={`${i.created_at}-${n}`}><td>{i.label}</td><td colSpan={10}>{i.status==='revoked'?'Invitation revoked':'Invitation not activated'} · created {date(i.created_at)}</td></tr>)}{!usage.testers.length&&!usage.invitations.length?<tr><td colSpan={11}>No beta invitations yet.</td></tr>:null}</tbody></table></div>
 <h3>Most consulted wallets · beta</h3><p>Ranked by opens, then distinct testers. Owner activity is excluded. Indexed transactions are the shared wallet total, not additional transactions charged to each viewer.</p><div className="usage-table-scroll"><table className="usage-table"><caption>Top 25 wallets by beta usage</caption><thead><tr><th>#</th><th>Wallet</th><th>Opens</th><th>Distinct testers</th><th>Transactions indexed</th><th>Last consulted</th></tr></thead><tbody>{usage.popularWallets.map((w,i)=><tr key={w.wallet_address}><td>{i+1}</td><td className="usage-wallet">{w.wallet_address}</td><td>{number(w.opens)}</td><td>{number(w.users)}</td><td>{number(w.transactions_indexed)}</td><td>{date(w.last_opened_at)}</td></tr>)}{!usage.popularWallets.length?<tr><td colSpan={6}>No beta wallet consultations recorded yet.</td></tr>:null}</tbody></table></div>
 {usage.owners.length?<><h3>Owner · excluded from beta totals</h3>{usage.owners.map(a=><p key={a.id}>{a.label} · {number(a.opens)} opens · {number(a.wallets)} distinct wallets · last activity {date(a.last_activity)}</p>)}</>:null}<p>New transactions count only saved work attributed to an analysis or extension request. Requests and extensions appear separately; errors remain attached to the failed request.</p></div>
}
