create table if not exists wallet_rewards (
  id bigint generated by default as identity primary key,
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  block_time timestamptz,
  reward_type text not null check (reward_type in ('CREATOR_FEE')),
  quote_mint text not null,
  quote_token_program text,
  amount numeric not null,
  raw_amount numeric not null,
  decimals integer not null default 0,
  creator text not null,
  creator_token_account text,
  creator_vault text,
  creator_vault_token_account text,
  instruction_index integer not null,
  source text,
  created_at timestamptz not null default now(),
  unique (wallet_address, signature, quote_mint, instruction_index)
);

create index if not exists idx_wallet_rewards_wallet_time
  on wallet_rewards(wallet_address, block_time desc);
create index if not exists idx_wallet_rewards_quote
  on wallet_rewards(quote_mint, block_time desc);