-- Run on the migrated database. Every fixture and change is rolled back.
begin;
do $$
declare a uuid; b uuid; r jsonb; balance integer; held integer; ord uuid;
 w text:='77777777777777777777777777777777'; fail_wallet text:='88888888888888888888888888888888';
begin
 if exists(select 1 from public.wallets where address in(w,fail_wallet)) then raise exception 'fixture_wallet_already_exists'; end if;
 perform public.credit_create_invite(repeat('a',64),'Integration A');
 a:=public.credit_login(repeat('a',64),repeat('b',64));
 perform public.credit_login(repeat('a',64),repeat('c',64));
 if (select count(*) from public.credit_accounts where id=a)<>1 or (select count(*) from public.credit_ledger where account_id=a)<>1 then raise exception 'login_replenished_balance'; end if;
 if (select expires_at-cycle_started_at from public.credit_accounts where id=a)<>interval '14 days' then raise exception 'wrong_expiry'; end if;
 perform public.credit_create_invite(repeat('d',64),'Integration B');
 b:=public.credit_login(repeat('d',64),repeat('e',64));
 if (select expires_at from public.credit_accounts where id=a) is distinct from (select expires_at from public.credit_accounts where id=b) then raise exception 'beta_deadlines_not_shared'; end if;
 begin perform public.credit_wallet_request(a,w,-1);raise exception 'trade_unlocked_unsaved_wallet'; exception when others then if sqlerrm<>'wallet_not_indexed' then raise; end if; end;
 r:=public.credit_wallet_request(a,w,0);
 if (r->>'reserved')::boolean is distinct from true then raise exception 'missing_reservation'; end if;
 if (select cycle_credits from public.credit_accounts where id=a)<>50 then raise exception 'charged_before_save'; end if;
 r:=public.credit_wallet_request(a,w,0);
 if (r->>'cost')::integer<>0 then raise exception 'duplicate_analysis_charged'; end if;
 begin perform public.credit_wallet_request(b,w,0);raise exception 'concurrent_account_allowed'; exception when others then if sqlerrm<>'wallet_analysis_in_progress' then raise; end if; end;
 update public.wallet_sync_state set transactions_scanned=1000 where wallet_address=w;
 update public.wallet_sync_state set transactions_scanned=1000 where wallet_address=w;
 if (select cycle_credits from public.credit_accounts where id=a)<>47 then raise exception 'checkpoint_double_charged'; end if;
 update public.wallet_sync_state set transactions_scanned=5000,status='idle' where wallet_address=w;
 if exists(select 1 from public.credit_requests where wallet_address=w and status='pending') then raise exception 'reservation_not_closed'; end if;
 r:=public.credit_wallet_request(b,w,0);r:=public.credit_wallet_request(b,w,0);
 if (select cycle_credits from public.credit_accounts where id=b)<>49 then raise exception 'unlock_not_once'; end if;
 r:=public.credit_wallet_request(a,w,10000);
 update public.wallet_sync_state set transactions_scanned=6000 where wallet_address=w;
 update public.wallet_sync_state set transactions_scanned=7000 where wallet_address=w;
 if (select cycle_credits from public.credit_accounts where id=a)<>46 then raise exception 'extension_rounding_per_page'; end if;
 update public.wallet_sync_state set transactions_scanned=7500,history_complete=true where wallet_address=w;
 if (select cycle_credits from public.credit_accounts where id=a)<>45 then raise exception 'partial_extension_wrong_cost'; end if;
 if exists(select 1 from public.credit_requests where wallet_address=w and status='pending') then raise exception 'unused_extension_not_released'; end if;
 r:=public.credit_wallet_request(a,fail_wallet,0);
 update public.wallet_index_jobs set status='error',last_error='test_write_failure' where wallet_address=fail_wallet;
 if exists(select 1 from public.credit_wallet_access where account_id=a and wallet_address=fail_wallet) then raise exception 'failed_analysis_access_retained'; end if;
 if exists(select 1 from public.credit_requests where wallet_address=fail_wallet and status='pending') then raise exception 'failed_reservation_not_released'; end if;
 if (select cycle_credits from public.credit_accounts where id=a)<>45 then raise exception 'failed_work_charged'; end if;
 update public.credit_accounts set cycle_credits=0 where id=b;
 r:=public.credit_wallet_request(b,w,0);
 if (r->>'cost')::integer<>0 then raise exception 'free_revisit_requires_credit'; end if;
 begin perform public.credit_wallet_request(b,fail_wallet,0);raise exception 'insufficient_balance_allowed'; exception when others then if sqlerrm<>'insufficient_credits' then raise; end if; end;
 update public.credit_accounts set expires_at=now()-interval '1 day' where id=b;
 begin perform public.credit_wallet_request(b,w,0);raise exception 'expired_access_allowed'; exception when others then if sqlerrm<>'subscription_expired' then raise; end if; end;
 perform public.credit_renew(a,'integration-pro-payment');
 perform public.credit_renew(a,'integration-pro-payment');
 if (select count(*) from public.credit_ledger where account_id=a and reason='pro_activation:integration-pro-payment')<>1 then raise exception 'renew_double_credited'; end if;
 if (select cycle_credits from public.credit_accounts where id=a)<>50 then raise exception 'renew_not_50'; end if;
 if (select expires_at-cycle_started_at from public.credit_accounts where id=a)<>interval '30 days' then raise exception 'pro_cycle_not_30_days'; end if;
 if not exists(select 1 from public.credit_wallet_access where account_id=a and wallet_address=w) then raise exception 'renew_lost_unlocks'; end if;
 insert into public.credit_orders(account_id) values(a) returning id into ord;
 perform public.credit_confirm_order(ord,'integration-pack-payment');perform public.credit_confirm_order(ord,'integration-pack-payment');
 if (select bonus_credits from public.credit_accounts where id=a)<>10 then raise exception 'pack_double_credited'; end if;
 begin perform public.credit_renew(a,'integration-pack-payment');raise exception 'payment_reused'; exception when others then if sqlerrm<>'payment_reference_reused' then raise; end if; end;
 if has_table_privilege('anon','public.credit_accounts','select') or has_function_privilege('anon','public.credit_wallet_request(uuid,text,integer)','execute') then raise exception 'public_credit_privileges'; end if;
end $$;
select 'PASS: login, expiry, reservation, duplicate requests, checkpoint billing, unlock-once, extension rounding, partial refund, failed writes, no balance, renewal, payment idempotence, RLS privileges' as result;
rollback;
