create table if not exists wallets (
  address text primary key,
  first_seen timestamptz,
  last_seen timestamptz,
  transaction_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists wallet_sync_state (
  wallet_address text primary key references wallets(address) on delete cascade,
  newest_signature text,
  newest_block_time timestamptz,
  oldest_signature text,
  oldest_block_time timestamptz,
  pages_scanned bigint not null default 0,
  status text not null default 'idle',
  last_synced_at timestamptz,
  last_deep_scan_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists wallet_transactions (
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  slot bigint,
  block_time timestamptz,
  tx_version text,
  parsed_type text,
  parser_reason text,
  raw_transaction jsonb,
  created_at timestamptz not null default now(),
  primary key (wallet_address, signature)
);

create table if not exists wallet_trades (
  id bigint generated by default as identity primary key,
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  block_time timestamptz,
  type text not null check (type in ('BUY','SELL')),
  token_mint text not null,
  token_amount numeric not null,
  sol_amount numeric not null,
  estimated_price_sol numeric,
  fee_sol numeric,
  dex text,
  parser text,
  created_at timestamptz not null default now(),
  unique (wallet_address, signature)
);

create table if not exists wallet_analysis_cache (
  wallet_address text primary key references wallets(address) on delete cascade,
  analysis_scope text not null default 'default',
  metrics jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  source_last_synced_at timestamptz
);

create table if not exists usage_events (
  id bigint generated by default as identity primary key,
  wallet_address text,
  user_id text,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_wallet_transactions_block_time
  on wallet_transactions(wallet_address, block_time desc);
create index if not exists idx_wallet_trades_wallet_time
  on wallet_trades(wallet_address, block_time desc);
create index if not exists idx_wallet_trades_token
  on wallet_trades(token_mint, block_time desc);
create index if not exists idx_usage_events_user_time
  on usage_events(user_id, created_at desc);
