create table if not exists wallets (
  address text primary key,
  first_seen timestamptz,
  last_seen timestamptz,
  transaction_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists wallet_sync_state (
  wallet_address text primary key references wallets(address) on delete cascade,
  newest_signature text,
  newest_block_time timestamptz,
  oldest_signature text,
  oldest_block_time timestamptz,
  pages_scanned bigint not null default 0,
  status text not null default 'idle',
  history_complete boolean not null default false,
  last_synced_at timestamptz,
  last_deep_scan_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists wallet_transactions (
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  slot bigint,
  block_time timestamptz,
  tx_version text,
  parsed_type text,
  parser_reason text,
  raw_transaction jsonb,
  created_at timestamptz not null default now(),
  primary key (wallet_address, signature)
);

create table if not exists wallet_trades (
  id bigint generated by default as identity primary key,
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  event_index integer not null default 0,
  block_time timestamptz,
  type text not null check (type in ('BUY','SELL')),
  token_mint text not null,
  token_amount numeric not null,
  sol_amount numeric not null,
  estimated_price_sol numeric,
  fee_sol numeric,
  dex text,
  parser text,
  created_at timestamptz not null default now(),
  unique (wallet_address, signature, event_index)
);

create table if not exists wallet_transfers (
  id bigint generated by default as identity primary key,
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  event_index integer not null default 0,
  instruction_index integer,
  block_time timestamptz,
  mint text not null,
  direction text not null check (direction in ('IN','OUT')),
  amount numeric not null,
  raw_amount numeric not null,
  decimals integer not null default 0,
  source_address text,
  destination_address text,
  source_token_account text,
  destination_token_account text,
  parser text,
  created_at timestamptz not null default now(),
  unique (wallet_address, signature, event_index)
);

create table if not exists wallet_rewards (
  id bigint generated by default as identity primary key,
  wallet_address text not null references wallets(address) on delete cascade,
  signature text not null,
  block_time timestamptz,
  reward_type text not null check (reward_type in ('CREATOR_FEE')),
  quote_mint text not null,
  quote_token_program text,
  amount numeric not null,
  raw_amount numeric not null,
  decimals integer not null default 0,
  creator text not null,
  creator_token_account text,
  creator_vault text,
  creator_vault_token_account text,
  instruction_index integer not null,
  source text,
  created_at timestamptz not null default now(),
  unique (wallet_address, signature, quote_mint, instruction_index)
);

create table if not exists wallet_analysis_cache (
  wallet_address text primary key references wallets(address) on delete cascade,
  analysis_scope text not null default 'default',
  metrics jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  source_last_synced_at timestamptz
);

create table if not exists usage_events (
  id bigint generated by default as identity primary key,
  wallet_address text,
  user_id text,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_wallet_transactions_block_time on wallet_transactions(wallet_address, block_time desc);
create index if not exists idx_wallet_trades_wallet_time on wallet_trades(wallet_address, block_time desc);
create index if not exists idx_wallet_trades_token on wallet_trades(token_mint, block_time desc);
create index if not exists idx_wallet_transfers_wallet_time on wallet_transfers(wallet_address, block_time desc);
create index if not exists idx_wallet_transfers_mint_time on wallet_transfers(mint, block_time desc);
create index if not exists idx_wallet_rewards_wallet_time on wallet_rewards(wallet_address, block_time desc);
create index if not exists idx_wallet_rewards_quote on wallet_rewards(quote_mint, block_time desc);
create index if not exists idx_usage_events_user_time on usage_events(user_id, created_at desc);

-- Safe upgrades for existing projects.
alter table wallet_sync_state add column if not exists history_complete boolean not null default false;
alter table wallet_trades add column if not exists event_index integer not null default 0;
alter table wallet_trades drop constraint if exists wallet_trades_wallet_address_signature_key;
create unique index if not exists idx_wallet_trades_event_unique on wallet_trades(wallet_address, signature, event_index);
