import {getWalletTradePage} from "./db.js";
import {buildTradeJourneys} from "./tradeJourneyEngine.js";
import {getPumpWalletProfile} from "./pumpProfile.js";
import {getPumpTokenMetadata} from "./pumpMetadata.js";
import {getJupiterTokenMetadata} from "./jupiterMetadata.js";
import {getTokenMetadata} from "./helius.js";
const BASE=String(process.env.SUPABASE_URL||"").replace(/\/$/,"");const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;const H={apikey:KEY,Authorization:`Bearer ${KEY}`};
async function q(path,options={}){const r=await fetch(`${BASE}/rest/v1/${path}`,{...options,headers:{...H,...(options.headers||{})}});if(!r.ok)throw new Error(`data trades ${r.status}`);const text=await r.text();return text?JSON.parse(text):null}
async function allTrades(wallet){let out=[];for(let offset=0;;offset+=1000){const page=await getWalletTradePage(wallet,1000,offset);out.push(...page);if(page.length<1000||out.length>=500000)break}return out.map(t=>({wallet:t.wallet_address,signature:t.signature,blockTime:t.block_time?Math.floor(new Date(t.block_time).getTime()/1000):null,type:t.type,tokenMint:t.token_mint,tokenAmount:Number(t.token_amount),solAmount:Number(t.sol_amount),estimatedPriceSol:Number(t.estimated_price_sol),feeSol:Number(t.fee_sol),dex:t.dex,parser:t.parser,slot:t.slot,eventIndex:t.event_index}))}
async function meta(mint){const[p,j,h]=await Promise.all([getPumpTokenMetadata(mint).catch(()=>null),getJupiterTokenMetadata(mint).catch(()=>null),getTokenMetadata(mint).catch(()=>null)]);const m=p||j||h||{};return{name:m.name||m.symbol||null,symbol:m.symbol||null}}
function publicJourney(j,wallet){return{journeyId:j.id,wallet,tokenMint:j.tokenMint,pnlSol:j.realizedPnl,pnlPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl,entryTime:j.entryTime,exitTime:j.exitTime,closed:j.closed}}
function formatHold(s){if(!Number.isFinite(s))return null;if(s<60)return`${Math.max(0,Math.round(s))}s`;if(s<3600)return`${Math.round(s/60)}m`;if(s<86400)return`${(s/3600).toFixed(s<36000?1:0)}h`;return`${(s/86400).toFixed(s<864000?1:0)}d`}
function dbJourney(r){return{journeyId:r.journey_id,wallet:r.wallet_address,tokenMint:r.token_mint,pnlSol:Number(r.pnl_sol),pnlPct:r.pnl_pct==null?null:Number(r.pnl_pct),holdSeconds:r.hold_seconds==null?null:Number(r.hold_seconds),hold:r.hold_seconds==null?null:formatHold(Number(r.hold_seconds)),costSol:r.cost_sol==null?null:Number(r.cost_sol),proceedsSol:r.proceeds_sol==null?null:Number(r.proceeds_sol),entryTime:r.entry_time?Math.floor(new Date(r.entry_time).getTime()/1000):null,exitTime:r.exit_time?Math.floor(new Date(r.exit_time).getTime()/1000):null,closed:r.closed}}
export async function persistTradeJourneys(wallet,journeys){const rows=(journeys||[]).filter(j=>j.closed&&Number.isFinite(j.realizedPnl)&&Number.isFinite(j.realizedCost)).map(j=>({wallet_address:wallet,journey_id:String(j.id),token_mint:j.tokenMint,pnl_sol:j.realizedPnl,pnl_pct:Number.isFinite(j.pnlPct)?j.pnlPct:null,hold_seconds:Number.isFinite(j.holdSeconds)?Math.round(j.holdSeconds):null,cost_sol:j.realizedCost,proceeds_sol:j.realizedCost+j.realizedPnl,entry_time:j.entryTime?new Date(j.entryTime*1000).toISOString():null,exit_time:j.exitTime?new Date(j.exitTime*1000).toISOString():null,closed:true,updated_at:new Date().toISOString()}));if(!rows.length)return 0;for(let i=0;i<rows.length;i+=500)await q("wallet_trade_journeys?on_conflict=wallet_address,journey_id",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows.slice(i,i+500))});return rows.length}
async function enrich(x){const[profile,token]=await Promise.all([getPumpWalletProfile(x.wallet).catch(()=>null),meta(x.tokenMint)]);return{...x,walletProfile:profile?{name:profile.displayName||profile.username,username:profile.username,avatar:profile.avatar||null}:null,token}}
export async function getTopDetectedTrades(limit=10){const rows=await q(`wallet_trade_journeys?select=wallet_address,journey_id,token_mint,pnl_sol,pnl_pct,hold_seconds,cost_sol,proceeds_sol,entry_time,exit_time,closed&closed=eq.true&pnl_sol=gt.0&order=pnl_sol.desc&limit=${Math.max(1,Math.min(100,Number(limit)||10))}`);return Promise.all((rows||[]).map(dbJourney).map(enrich))}
async function rpc(method,params){const key=process.env.HELIUS_API_KEY;if(!key)return null;try{const r=await fetch(`https://mainnet.helius-rpc.com/?api-key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:'mcap',method,params})});const x=await r.json();return x?.result||null}catch{return null}}
async function currentSupply(mint){const r=await rpc('getTokenSupply',[mint,{commitment:'confirmed'}]);const v=Number(r?.value?.uiAmountString??r?.value?.uiAmount);return Number.isFinite(v)&&v>0?v:null}
async function solUsdAt(ts){if(!ts)return null;try{const from=ts-1800,to=ts+1800,u=`https://api.coingecko.com/api/v3/coins/solana/market_chart/range?vs_currency=usd&from=${from}&to=${to}`;const r=await fetch(u,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(5000)});if(!r.ok)return null;const x=await r.json(),rows=Array.isArray(x?.prices)?x.prices:[];if(!rows.length)return null;rows.sort((a,b)=>Math.abs(a[0]/1000-ts)-Math.abs(b[0]/1000-ts));return Number(rows[0][1])||null}catch{return null}}
async function estimateMcap(event,supply){if(!(supply>0))return{marketCap:null,marketCapStatus:'unavailable'};const quotePrice=Number(event.estimatedPriceSol);if(!(quotePrice>0))return{marketCap:null,marketCapStatus:'unavailable'};const solUsd=await solUsdAt(event.blockTime);if(!(solUsd>0))return{marketCap:null,marketCapStatus:'unavailable'};return{marketCap:quotePrice*supply*solUsd,marketCapStatus:'estimated_current_supply',marketCapQuote:'SOL',quoteUsd:solUsd,supplyUsed:supply}}
export async function getTradeDetail(wallet,mint,journeyId=null){const journeys=buildTradeJourneys((await allTrades(wallet)).filter(t=>t.tokenMint===mint));if(!journeys.length)return null;const j=(journeyId&&journeys.find(x=>x.id===journeyId))||[...journeys].sort((a,b)=>b.realizedPnl-a.realizedPnl)[0];const[profile,token,supply]=await Promise.all([getPumpWalletProfile(wallet).catch(()=>null),meta(mint),currentSupply(mint)]);const events=[];for(const e of j.events){const mc=await estimateMcap(e,supply);events.push({...e,...mc})}const entry=events.find(e=>e.type==='BUY'),exit=[...events].reverse().find(e=>e.type==='SELL');return{...publicJourney(j,wallet),walletProfile:profile?{name:profile.displayName||profile.username,username:profile.username,avatar:profile.avatar||null}:null,token,summary:{pnlSol:j.realizedPnl,pnlPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl,entryMarketCap:entry?.marketCap??null,exitMarketCap:exit?.marketCap??null,marketCapStatus:supply?'estimated_current_supply':'unavailable'},events}}
