import {getWalletTradePage} from "./db.js";
import {buildTradeJourneys} from "./tradeJourneyEngine.js";
import {getPumpWalletProfile} from "./pumpProfile.js";
import {getPumpTokenMetadata} from "./pumpMetadata.js";
import {getJupiterTokenMetadata} from "./jupiterMetadata.js";
import {getTokenMetadata} from "./helius.js";
const BASE=String(process.env.SUPABASE_URL||"").replace(/\/$/,"");const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;const H={apikey:KEY,Authorization:`Bearer ${KEY}`};
async function q(path){const r=await fetch(`${BASE}/rest/v1/${path}`,{headers:H});if(!r.ok)throw new Error(`data trades ${r.status}`);return r.json()}
async function wallets(){return q("wallets?select=address&order=last_seen.desc&limit=100")}
async function allTrades(wallet){let out=[];for(let offset=0;;offset+=1000){const page=await getWalletTradePage(wallet,1000,offset);out.push(...page);if(page.length<1000||out.length>=50000)break}return out.map(t=>({wallet:t.wallet_address,signature:t.signature,blockTime:t.block_time?Math.floor(new Date(t.block_time).getTime()/1000):null,type:t.type,tokenMint:t.token_mint,tokenAmount:Number(t.token_amount),solAmount:Number(t.sol_amount),estimatedPriceSol:Number(t.estimated_price_sol),feeSol:Number(t.fee_sol),dex:t.dex,parser:t.parser,slot:t.slot,eventIndex:t.event_index}))}
async function meta(mint){const[p,j,h]=await Promise.all([getPumpTokenMetadata(mint).catch(()=>null),getJupiterTokenMetadata(mint).catch(()=>null),getTokenMetadata(mint).catch(()=>null)]);const m=p||j||h||{};return{name:m.name||m.symbol||null,symbol:m.symbol||null}}
async function rpc(method,params){const key=process.env.HELIUS_API_KEY;if(!key)return null;try{const r=await fetch(`https://mainnet.helius-rpc.com/?api-key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:'mcap',method,params})});const x=await r.json();return x?.result||null}catch{return null}}
async function currentSupply(mint){const r=await rpc('getTokenSupply',[mint,{commitment:'confirmed'}]);const v=Number(r?.value?.uiAmountString??r?.value?.uiAmount);return Number.isFinite(v)&&v>0?v:null}
async function solUsdAt(ts){if(!ts)return null;try{const from=ts-1800,to=ts+1800,u=`https://api.coingecko.com/api/v3/coins/solana/market_chart/range?vs_currency=usd&from=${from}&to=${to}`;const r=await fetch(u,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(5000)});if(!r.ok)return null;const x=await r.json(),rows=Array.isArray(x?.prices)?x.prices:[];if(!rows.length)return null;rows.sort((a,b)=>Math.abs(a[0]/1000-ts)-Math.abs(b[0]/1000-ts));return Number(rows[0][1])||null}catch{return null}}
async function estimateMcap(event,supply){if(!(supply>0))return{marketCap:null,marketCapStatus:'unavailable'};const quotePrice=Number(event.estimatedPriceSol);if(!(quotePrice>0))return{marketCap:null,marketCapStatus:'unavailable'};const solUsd=await solUsdAt(event.blockTime);if(!(solUsd>0))return{marketCap:null,marketCapStatus:'unavailable'};return{marketCap:quotePrice*supply*solUsd,marketCapStatus:'estimated_current_supply',marketCapQuote:'SOL',quoteUsd:solUsd,supplyUsed:supply}}
function publicJourney(j,wallet){return{journeyId:j.id,wallet,tokenMint:j.tokenMint,pnlSol:j.realizedPnl,pnlPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl,entryTime:j.entryTime,exitTime:j.exitTime,closed:j.closed}}
export async function getTopDetectedTrades(limit=10){const ws=await wallets(),candidates=[];for(const{address}of ws){const journeys=buildTradeJourneys(await allTrades(address));for(const j of journeys)if(j.closed&&j.realizedPnl>0&&j.realizedCost>0)candidates.push(publicJourney(j,address))}candidates.sort((a,b)=>b.pnlSol-a.pnlSol);return Promise.all(candidates.slice(0,limit).map(async x=>{const[profile,token]=await Promise.all([getPumpWalletProfile(x.wallet).catch(()=>null),meta(x.tokenMint)]);return{...x,walletProfile:profile?{name:profile.displayName||profile.username,username:profile.username,avatar:profile.avatar||null}:null,token}}))}
export async function getTradeDetail(wallet,mint,journeyId=null){const journeys=buildTradeJourneys((await allTrades(wallet)).filter(t=>t.tokenMint===mint));if(!journeys.length)return null;const j=(journeyId&&journeys.find(x=>x.id===journeyId))||[...journeys].sort((a,b)=>b.realizedPnl-a.realizedPnl)[0];const[profile,token,supply]=await Promise.all([getPumpWalletProfile(wallet).catch(()=>null),meta(mint),currentSupply(mint)]);const events=[];for(const e of j.events){const mc=await estimateMcap(e,supply);events.push({...e,...mc})}const entry=events.find(e=>e.type==='BUY'),exit=[...events].reverse().find(e=>e.type==='SELL');return{...publicJourney(j,wallet),walletProfile:profile?{name:profile.displayName||profile.username,username:profile.username,avatar:profile.avatar||null}:null,token,summary:{pnlSol:j.realizedPnl,pnlPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl,entryMarketCap:entry?.marketCap??null,exitMarketCap:exit?.marketCap??null,marketCapStatus:supply?'estimated_current_supply':'unavailable'},events}}
