import {assertWalletReadable,excludedWallets} from "./walletPolicy.js";
import {getWalletTradePage,getWalletTransferPage,getWalletRewardsPage} from "./db.js";
import {buildTradeJourneys} from "./tradeJourneyEngine.js";
import {getPumpWalletProfile} from "./pumpProfile.js";
import {getPumpTokenMetadata} from "./pumpMetadata.js";
import {getJupiterTokenMetadata} from "./jupiterMetadata.js";
import {getTokenMetadata} from "./helius.js";
const BASE=String(process.env.SUPABASE_URL||"").replace(/\/$/,"");const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;const H={apikey:KEY,Authorization:`Bearer ${KEY}`};
async function q(path,options={}){const r=await fetch(`${BASE}/rest/v1/${path}`,{...options,headers:{...H,...(options.headers||{})}});if(!r.ok)throw new Error(`data trades ${r.status}`);const text=await r.text();return text?JSON.parse(text):null}
async function allTrades(wallet,mint=null){let out=[];for(let offset=0;;offset+=1000){const page=await getWalletTradePage(wallet,1000,offset,mint);out.push(...page);if(page.length<1000)break;if(out.length>=500000)throw new Error("trade_history_limit_exceeded")}return out.map(t=>({wallet:t.wallet_address,signature:t.signature,blockTime:t.block_time?Math.floor(new Date(t.block_time).getTime()/1000):null,type:t.type,tokenMint:t.token_mint,tokenAmount:Number(t.token_amount),solAmount:Number(t.sol_amount),estimatedPriceSol:Number(t.estimated_price_sol),feeSol:Number(t.fee_sol),dex:t.dex,parser:t.parser,slot:t.slot==null?null:Number(t.slot),eventIndex:Number(t.event_index)||0}))}
async function inventoryEvents(wallet,mint){
 const read=async fn=>{const rows=[];for(let offset=0;offset<500000;offset+=1000){const page=await fn(wallet,1000,offset,mint);rows.push(...page);if(page.length<1000)return rows}throw new Error("inventory_history_limit_exceeded")};
 const[transfers,rewards]=await Promise.all([read(getWalletTransferPage),read(getWalletRewardsPage)]);
 const common=r=>({signature:r.signature,slot:r.slot==null?null:Number(r.slot),blockTime:r.block_time?Math.floor(new Date(r.block_time).getTime()/1000):null});
 return{transfers:transfers.map(r=>({...common(r),mint:r.token_mint,amount:Number(r.token_amount),direction:r.direction,eventIndex:Number(r.event_index)||0})),rewards:rewards.map(r=>({...common(r),quoteMint:r.quote_mint,amount:Number(r.amount),instructionIndex:Number(r.instruction_index)||0}))};
}
async function meta(mint){const[p,j,h]=await Promise.all([getPumpTokenMetadata(mint).catch(()=>null),getJupiterTokenMetadata(mint).catch(()=>null),getTokenMetadata(mint).catch(()=>null)]);const m=p||j||h||{};return{name:m.name||m.symbol||null,symbol:m.symbol||null}}
function publicJourney(j,wallet){return{journeyId:j.id,legacyJourneyId:j.legacyId,wallet,tokenMint:j.tokenMint,pnlSol:j.realizedPnl,pnlPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl,entryTime:j.entryTime,exitTime:j.exitTime,closed:j.closed}}
function formatHold(s){if(!Number.isFinite(s))return null;if(s<60)return`${Math.max(0,Math.round(s))}s`;if(s<3600)return`${Math.round(s/60)}m`;if(s<86400)return`${(s/3600).toFixed(s<36000?1:0)}h`;return`${(s/86400).toFixed(s<864000?1:0)}d`}
function dbJourney(r){return{journeyId:r.journey_id,wallet:r.wallet_address,tokenMint:r.token_mint,pnlSol:Number(r.pnl_sol),pnlPct:r.pnl_pct==null?null:Number(r.pnl_pct),holdSeconds:r.hold_seconds==null?null:Number(r.hold_seconds),hold:r.hold_seconds==null?null:formatHold(Number(r.hold_seconds)),costSol:r.cost_sol==null?null:Number(r.cost_sol),proceedsSol:r.proceeds_sol==null?null:Number(r.proceeds_sol),entryTime:r.entry_time?Math.floor(new Date(r.entry_time).getTime()/1000):null,exitTime:r.exit_time?Math.floor(new Date(r.exit_time).getTime()/1000):null,closed:r.closed}}
export async function persistTradeJourneys(wallet,journeys){const ids=new Map();for(const j of journeys||[])ids.set(j.id,(ids.get(j.id)||0)+1);const rows=(journeys||[]).filter(j=>ids.get(j.id)===1&&j.closed&&Number.isFinite(j.realizedPnl)&&Number.isFinite(j.realizedCost)).map(j=>({wallet_address:wallet,journey_id:String(j.id),token_mint:j.tokenMint,pnl_sol:j.realizedPnl,pnl_pct:Number.isFinite(j.pnlPct)?j.pnlPct:null,hold_seconds:Number.isFinite(j.holdSeconds)?Math.round(j.holdSeconds):null,cost_sol:j.realizedCost,proceeds_sol:j.realizedCost+j.realizedPnl,entry_time:Number.isFinite(j.entryTime)&&Number.isFinite(new Date(j.entryTime*1000).getTime())?new Date(j.entryTime*1000).toISOString():null,exit_time:Number.isFinite(j.exitTime)&&Number.isFinite(new Date(j.exitTime*1000).getTime())?new Date(j.exitTime*1000).toISOString():null,closed:true,updated_at:new Date().toISOString()}));await q("rpc/replace_wallet_trade_journeys",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({p_wallet:wallet,p_rows:rows})});return rows.length}
async function enrich(x){const[profile,token]=await Promise.all([getPumpWalletProfile(x.wallet).catch(()=>null),meta(x.tokenMint)]);return{...x,walletProfile:profile?{name:profile.displayName||profile.username,username:profile.username,avatar:profile.avatar||null}:null,token}}
export function selectRankedJourneys(rows,limit=10){
  const current=new Set((rows||[]).filter(r=>String(r.journey_id).includes(":v2:")).map(r=>`${r.wallet_address}:${r.token_mint}:${r.entry_time?Math.floor(new Date(r.entry_time).getTime()/1000):0}`));
  const seen=new Set();return(rows||[]).filter(r=>{
    const key=`${r.wallet_address}:${r.journey_id}`;
    if(seen.has(key))return false;seen.add(key);
    return String(r.journey_id).includes(":v2:")||!current.has(key);
  }).slice(0,Math.max(1,Math.min(100,Number(limit)||10)));
}
export async function getTopDetectedTrades(limit=10){const rows=await q(`wallet_trade_journeys?select=wallet_address,journey_id,token_mint,pnl_sol,pnl_pct,hold_seconds,cost_sol,proceeds_sol,entry_time,exit_time,closed&closed=eq.true&analysis_version=eq.3&pnl_sol=gt.0&order=pnl_sol.desc&limit=100`);const excluded=await excludedWallets();const wallets=[...new Set(rows.map(r=>r.wallet_address))];const complete=wallets.length?await q(`wallet_sync_state?select=wallet_address&history_complete=eq.true&wallet_address=in.(${wallets.map(encodeURIComponent).join(",")})`):[];const eligible=new Set(complete.map(r=>r.wallet_address));return Promise.all(selectRankedJourneys(rows.filter(r=>!excluded.has(r.wallet_address)&&eligible.has(r.wallet_address)),limit).map(dbJourney).map(enrich))}
export async function getTradeDetail(wallet,mint,journeyId=null){await assertWalletReadable(wallet);const [trades,inventory]=await Promise.all([allTrades(wallet,mint),inventoryEvents(wallet,mint)]);const journeys=buildTradeJourneys(trades.filter(t=>t.tokenMint===mint),inventory.transfers,inventory.rewards);if(!journeys.length)return null;const matches=journeyId!==null?journeys.filter(x=>x.id===journeyId||x.legacyId===journeyId):null;if(matches&&matches.length!==1)return null;const j=matches?matches[0]:[...journeys].sort((a,b)=>b.realizedPnl-a.realizedPnl)[0];const[profile,token]=await Promise.all([getPumpWalletProfile(wallet).catch(()=>null),meta(mint)]);return{...publicJourney(j,wallet),walletProfile:profile?{name:profile.displayName||profile.username,username:profile.username,avatar:profile.avatar||null}:null,token,summary:{pnlSol:j.realizedPnl,pnlPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl},events:j.events}}

