import { getTransactionsForAddress } from "./helius.js";
import { parseTransaction } from "./parser.js";

const wallet =
  "CjfLyafnK76qJyfTnBF8wb2H15D3bnMVNbRESmByDtmX";

  const targetMint =
    "BXrbjRfUH35Y9fDxmHw9GambqVHZ6McmgfRXGqkzUjQr";

    try {
      console.log("");
        console.log("MONFLUXO TOKEN DEBUG");
          console.log("====================");
            console.log("Wallet:", wallet);
              console.log("Token:", targetMint);
                console.log("");

                  const allTransactions = [];

                    let paginationToken = null;
                      let page = 1;
                        const maxPages = 5;

                          while (page <= maxPages) {
                              console.log(`Loading page ${page}...`);

                                  const result =
                                        await getTransactionsForAddress(
                                                wallet,
                                                        paginationToken
                                                              );

                                                                  const transactions =
                                                                        result?.data || [];

                                                                            console.log(
                                                                                  `Page ${page}: ${transactions.length} transactions`
                                                                                      );

                                                                                          if (transactions.length === 0) {
                                                                                                break;
                                                                                                    }

                                                                                                        allTransactions.push(
                                                                                                              ...transactions
                                                                                                                  );

                                                                                                                      paginationToken =
                                                                                                                            result?.paginationToken || null;

                                                                                                                                if (!paginationToken) {
                                                                                                                                      break;
                                                                                                                                          }

                                                                                                                                              page++;
                                                                                                                                                }

                                                                                                                                                  const trades = [];

                                                                                                                                                    for (const transaction of allTransactions) {
                                                                                                                                                        const analysis =
                                                                                                                                                              parseTransaction(
                                                                                                                                                                      transaction,
                                                                                                                                                                              wallet
                                                                                                                                                                                    );

                                                                                                                                                                                        if (!analysis.trade) {
                                                                                                                                                                                              continue;
                                                                                                                                                                                                  }

                                                                                                                                                                                                      if (
                                                                                                                                                                                                            analysis.trade.tokenMint !==
                                                                                                                                                                                                                  targetMint
                                                                                                                                                                                                                      ) {
                                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                    trades.push({
                                                                                                                                                                                                                                          ...analysis.trade,

                                                                                                                                                                                                                                                signature:
                                                                                                                                                                                                                                                        transaction?.transaction
                                                                                                                                                                                                                                                                  ?.signatures?.[0] ||
                                                                                                                                                                                                                                                                          transaction?.signature ||
                                                                                                                                                                                                                                                                                  null,

                                                                                                                                                                                                                                                                                        blockTime:
                                                                                                                                                                                                                                                                                                transaction?.blockTime ||
                                                                                                                                                                                                                                                                                                        null
                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                trades.sort(
                                                                                                                                                                                                                                                                                                                    (a, b) =>
                                                                                                                                                                                                                                                                                                                          (a.blockTime || 0) -
                                                                                                                                                                                                                                                                                                                                (b.blockTime || 0)
                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                    console.log("");
                                                                                                                                                                                                                                                                                                                                      console.log("====================");
                                                                                                                                                                                                                                                                                                                                        console.log("TOKEN TRADES");
                                                                                                                                                                                                                                                                                                                                          console.log("====================");

                                                                                                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                                                                                                "Trades found:",
                                                                                                                                                                                                                                                                                                                                                    trades.length
                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                        let totalBought = 0;
                                                                                                                                                                                                                                                                                                                                                          let totalSold = 0;

                                                                                                                                                                                                                                                                                                                                                            trades.forEach(
                                                                                                                                                                                                                                                                                                                                                                (trade, index) => {
                                                                                                                                                                                                                                                                                                                                                                      console.log("");
                                                                                                                                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                                                                                                                                    `#${index + 1} ${trade.type}`
                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                                                                                                        "Token amount:",
                                                                                                                                                                                                                                                                                                                                                                                                                trade.tokenAmount
                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                    "SOL amount:",
                                                                                                                                                                                                                                                                                                                                                                                                                                            trade.solAmount
                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Price:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trade.estimatedPriceSol
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Block time:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    trade.blockTime
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Signature:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                trade.signature
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (trade.type === "BUY") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    totalBought +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              trade.tokenAmount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (trade.type === "SELL") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  totalSold +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            trade.tokenAmount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("====================");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("TOTALS");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("====================");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Total bought:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          totalBought
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Total sold:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      totalSold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Difference:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  totalBought - totalSold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("====================");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("END DEBUG");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("====================");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Debug error:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }