import { getTransactionsForAddress } from "./helius.js";

const wallet =
  "CjfLyafnK76qJyfTnBF8wb2H15D3bnMVNbRESmByDtmX";

  const targetMint =
    "BXrbjRfUH35Y9fDxmHw9GambqVHZ6McmgfRXGqkzUjQr";

    try {
      console.log("");
        console.log("MONFLUXO BXRB TRANSACTION DEBUG");
          console.log("================================");
            console.log("");

              let paginationToken = null;
                let page = 1;
                  const maxPages = 100;

                    let found = 0;

                      while (page <= maxPages) {
                          const result =
                                await getTransactionsForAddress(
                                        wallet,
                                                paginationToken,
                                                        "desc"
                                                              );

                                                                  const transactions =
                                                                        result?.data || [];

                                                                            console.log(
                                                                                  `Loading page ${page}...`
                                                                                      );

                                                                                          console.log(
                                                                                                `Page ${page}: ${transactions.length} transactions`
                                                                                                    );

                                                                                                        if (transactions.length === 0) {
                                                                                                              break;
                                                                                                                  }

                                                                                                                      for (const transaction of transactions) {
                                                                                                                            const pre =
                                                                                                                                    transaction?.meta?.preTokenBalances || [];

                                                                                                                                          const post =
                                                                                                                                                  transaction?.meta?.postTokenBalances || [];

                                                                                                                                                        const balances = [
                                                                                                                                                                ...pre,
                                                                                                                                                                        ...post
                                                                                                                                                                              ];

                                                                                                                                                                                    const relevant =
                                                                                                                                                                                            balances.some(
                                                                                                                                                                                                      (balance) =>
                                                                                                                                                                                                                  balance.mint === targetMint
                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                if (!relevant) {
                                                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                    found++;

                                                                                                                                                                                                                                                          // Solo queremos el evento #71
                                                                                                                                                                                                                                                                if (found !== 71) {
                                                                                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                    const signature =
                                                                                                                                                                                                                                                                                            transaction?.transaction
                                                                                                                                                                                                                                                                                                      ?.signatures?.[0] ||
                                                                                                                                                                                                                                                                                                              transaction?.signature ||
                                                                                                                                                                                                                                                                                                                      null;

                                                                                                                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                                                                                                                  console.log("================================");
                                                                                                                                                                                                                                                                                                                                        console.log("BXRB EVENT #71");
                                                                                                                                                                                                                                                                                                                                              console.log("================================");

                                                                                                                                                                                                                                                                                                                                                    console.log("");
                                                                                                                                                                                                                                                                                                                                                          console.log("SIGNATURE");
                                                                                                                                                                                                                                                                                                                                                                console.log("---------");
                                                                                                                                                                                                                                                                                                                                                                      console.log(signature);

                                                                                                                                                                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                                                                                                                                                                  console.log("BLOCK TIME");
                                                                                                                                                                                                                                                                                                                                                                                        console.log("----------");
                                                                                                                                                                                                                                                                                                                                                                                              console.log(transaction?.blockTime);

                                                                                                                                                                                                                                                                                                                                                                                                    console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                          console.log("SLOT");
                                                                                                                                                                                                                                                                                                                                                                                                                console.log("----");
                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(transaction?.slot);

                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("ACCOUNT KEYS");
                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("-----------");

                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                transaction?.transaction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?.message?.accountKeys || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("OUTER INSTRUCTIONS");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("------------------");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transaction?.transaction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?.message?.instructions || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("INNER INSTRUCTIONS");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("------------------");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transaction?.meta
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?.innerInstructions || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("LOG MESSAGES");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("------------");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transaction?.meta
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?.logMessages || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("PRE TOKEN BALANCES");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("------------------");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pre,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("POST TOKEN BALANCES");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("-------------------");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            post,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("RAW TRANSACTION");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("---------------");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              JSON.stringify(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transaction,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log("================================");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("END EVENT #71");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log("================================");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        process.exit(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                paginationToken =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      result?.paginationToken || null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!paginationToken) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        page++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("Event #71 not found.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Debug error:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }