import { getTransactionsForAddress } from "./helius.js";
import { parseTransaction } from "./parser.js";

const wallet = process.argv[2];

if (!wallet) {
  console.error("Usage: npm start <wallet_address>");
    process.exit(1);
    }

    try {
      console.log("");
        console.log("MONFLUXO WALLET ANALYZER");
          console.log("========================");
            console.log("Wallet:", wallet);
              console.log("");

                const allTransactions = [];

                  let paginationToken = null;
                    let page = 1;
                      const maxPages = 5;

                        while (page <= maxPages) {
                            console.log(`Loading page ${page}...`);

                                const result = await getTransactionsForAddress(
                                      wallet,
                                            paginationToken
                                                );

                                                    const transactions =
                                                          result?.data || [];

                                                              console.log(
                                                                    `Page ${page}: ${transactions.length} transactions`
                                                                        );

                                                                            if (transactions.length === 0) {
                                                                                  break;
                                                                                      }

                                                                                          allTransactions.push(
                                                                                                ...transactions
                                                                                                    );

                                                                                                        paginationToken =
                                                                                                              result?.paginationToken || null;

                                                                                                                  if (!paginationToken) {
                                                                                                                        break;
                                                                                                                            }

                                                                                                                                page++;
                                                                                                                                  }

                                                                                                                                    console.log("");
                                                                                                                                      console.log(
                                                                                                                                          "Total transactions loaded:",
                                                                                                                                              allTransactions.length
                                                                                                                                                );
                                                                                                                                                  console.log("");

                                                                                                                                                    let tradesFound = 0;

                                                                                                                                                      for (const transaction of allTransactions) {
                                                                                                                                                          const analysis =
                                                                                                                                                                parseTransaction(
                                                                                                                                                                        transaction,
                                                                                                                                                                                wallet
                                                                                                                                                                                      );

                                                                                                                                                                                          if (
                                                                                                                                                                                                analysis.type !== "BUY" &&
                                                                                                                                                                                                      analysis.type !== "SELL"
                                                                                                                                                                                                          ) {
                                                                                                                                                                                                                continue;
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        tradesFound++;

                                                                                                                                                                                                                            console.log("");
                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                      "TRADE #" + tradesFound
                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                    "--------"
                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                  "Signature:",
                                                                                                                                                                                                                                                                        transaction?.transaction?.signatures?.[0] ||
                                                                                                                                                                                                                                                                              transaction?.signature ||
                                                                                                                                                                                                                                                                                    "Unknown"
                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                            console.log(
                                                                                                                                                                                                                                                                                                  "Type:",
                                                                                                                                                                                                                                                                                                        analysis.type
                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                      "Reason:",
                                                                                                                                                                                                                                                                                                                            analysis.reason
                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                    for (
                                                                                                                                                                                                                                                                                                                                          const token of analysis.tokenChanges
                                                                                                                                                                                                                                                                                                                                              ) {
                                                                                                                                                                                                                                                                                                                                                    console.log(
                                                                                                                                                                                                                                                                                                                                                            "Mint:",
                                                                                                                                                                                                                                                                                                                                                                    token.mint
                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                                                                                        "Token amount:",
                                                                                                                                                                                                                                                                                                                                                                                                Math.abs(
                                                                                                                                                                                                                                                                                                                                                                                                          Number(token.rawChange)
                                                                                                                                                                                                                                                                                                                                                                                                                  ) /
                                                                                                                                                                                                                                                                                                                                                                                                                          10 ** token.decimals
                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                              "Direction:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      token.direction
                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (analysis.solChange) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "SOL:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Math.abs(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    analysis.solChange.solChange
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (analysis.trade) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Estimated price:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                analysis.trade.estimatedPriceSol
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "========================"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "MONFLUXO ANALYSIS COMPLETE"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "========================"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Transactions loaded:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  allTransactions.length
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Trades detected:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tradesFound
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Error:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }