import { getTransactionsForAddress } from "./helius.js";
import { parseTransaction } from "./parser.js";
import { buildPositions } from "./positionEngine.js";

const wallet = process.argv[2];

if (!wallet) {
  console.error("Usage: npm start <wallet_address>");
    process.exit(1);
    }

    try {
      console.log("");
        console.log("MONFLUXO WALLET ANALYZER");
          console.log("========================");
            console.log("Wallet:", wallet);
              console.log("");

                const allTransactions = [];

                  let paginationToken = null;
                    let page = 1;
                      const maxPages = 5;

                        while (page <= maxPages) {
                            console.log(`Loading page ${page}...`);

                                const result = await getTransactionsForAddress(
                                      wallet,
                                            paginationToken
                                                );

                                                    const transactions = result?.data || [];

                                                        console.log(
                                                              `Page ${page}: ${transactions.length} transactions`
                                                                  );

                                                                      if (transactions.length === 0) {
                                                                            break;
                                                                                }

                                                                                    allTransactions.push(...transactions);

                                                                                        paginationToken =
                                                                                              result?.paginationToken || null;

                                                                                                  if (!paginationToken) {
                                                                                                        break;
                                                                                                            }

                                                                                                                page++;
                                                                                                                  }

                                                                                                                    const trades = [];

                                                                                                                      for (const transaction of allTransactions) {
                                                                                                                          const analysis =
                                                                                                                                parseTransaction(transaction, wallet);

                                                                                                                                    if (
                                                                                                                                          analysis.type !== "BUY" &&
                                                                                                                                                analysis.type !== "SELL"
                                                                                                                                                    ) {
                                                                                                                                                          continue;
                                                                                                                                                              }

                                                                                                                                                                  if (!analysis.trade) {
                                                                                                                                                                        continue;
                                                                                                                                                                            }

                                                                                                                                                                                trades.push({
                                                                                                                                                                                      ...analysis.trade,
                                                                                                                                                                                            signature:
                                                                                                                                                                                                    transaction?.transaction?.signatures?.[0] ||
                                                                                                                                                                                                            transaction?.signature ||
                                                                                                                                                                                                                    null,
                                                                                                                                                                                                                          blockTime:
                                                                                                                                                                                                                                  transaction?.blockTime || null
                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                          const positions =
                                                                                                                                                                                                                                              buildPositions(trades);

                                                                                                                                                                                                                                                let totalRealizedPnl = 0;
                                                                                                                                                                                                                                                  let openPositions = 0;

                                                                                                                                                                                                                                                    for (const position of positions.values()) {
                                                                                                                                                                                                                                                        totalRealizedPnl +=
                                                                                                                                                                                                                                                              position.realizedPnl;

                                                                                                                                                                                                                                                                  if (position.tokensRemaining > 0.000000001) {
                                                                                                                                                                                                                                                                        openPositions++;
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                console.log("");
                                                                                                                                                                                                                                                                                  console.log("========================");
                                                                                                                                                                                                                                                                                    console.log("POSITION ENGINE");
                                                                                                                                                                                                                                                                                      console.log("========================");

                                                                                                                                                                                                                                                                                        console.log("");
                                                                                                                                                                                                                                                                                          console.log("Trades analyzed:", trades.length);
                                                                                                                                                                                                                                                                                            console.log("Unique tokens:", positions.size);
                                                                                                                                                                                                                                                                                              console.log("Open positions:", openPositions);

                                                                                                                                                                                                                                                                                                console.log("");
                                                                                                                                                                                                                                                                                                  console.log("REALIZED PNL");
                                                                                                                                                                                                                                                                                                    console.log("------------");

                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                          "Realized PnL:",
                                                                                                                                                                                                                                                                                                              totalRealizedPnl.toFixed(6),
                                                                                                                                                                                                                                                                                                                  "SOL"
                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                      console.log("");
                                                                                                                                                                                                                                                                                                                        console.log("POSITIONS");
                                                                                                                                                                                                                                                                                                                          console.log("---------");

                                                                                                                                                                                                                                                                                                                            const sortedPositions =
                                                                                                                                                                                                                                                                                                                                [...positions.values()]
                                                                                                                                                                                                                                                                                                                                      .sort(
                                                                                                                                                                                                                                                                                                                                              (a, b) =>
                                                                                                                                                                                                                                                                                                                                                        Math.abs(b.realizedPnl) -
                                                                                                                                                                                                                                                                                                                                                                  Math.abs(a.realizedPnl)
                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                          sortedPositions
                                                                                                                                                                                                                                                                                                                                                                              .slice(0, 10)
                                                                                                                                                                                                                                                                                                                                                                                  .forEach((position, index) => {
                                                                                                                                                                                                                                                                                                                                                                                        console.log("");
                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                      `${index + 1}. ${position.mint}`
                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                          "Buys:",
                                                                                                                                                                                                                                                                                                                                                                                                                                  position.buys
                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Sells:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              position.sells
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Tokens bought:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position.tokensBought
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Tokens sold:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      position.tokensSold
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Tokens remaining:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  position.tokensRemaining
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "SOL spent:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              position.solSpent.toFixed(6)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "SOL received:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position.solReceived.toFixed(6)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "Realized PnL:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      position.realizedPnl.toFixed(6),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "SOL"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("========================");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("MONFLUXO ANALYSIS COMPLETE");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("========================");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Error:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }