export function buildPositions(trades) {
      const positions = new Map();

        for (const trade of trades) {
            const mint = trade.tokenMint;

                if (!positions.has(mint)) {
                      positions.set(mint, {
                              mint,
                                      buys: 0,
                                              sells: 0,
                                                      tokensBought: 0,
                                                              tokensSold: 0,
                                                                      tokensRemaining: 0,
                                                                              solSpent: 0,
                                                                                      solReceived: 0,
                                                                                              realizedPnl: 0,
                                                                                                      lots: []
                                                                                                            });
                                                                                                                }

                                                                                                                    const position = positions.get(mint);

                                                                                                                        if (trade.type === "BUY") {
                                                                                                                              position.buys++;

                                                                                                                                    position.tokensBought +=
                                                                                                                                            trade.tokenAmount;

                                                                                                                                                  position.solSpent +=
                                                                                                                                                          trade.solAmount;

                                                                                                                                                                position.lots.push({
                                                                                                                                                                        tokens:
                                                                                                                                                                                  trade.tokenAmount,

                                                                                                                                                                                          costSol:
                                                                                                                                                                                                    trade.solAmount,

                                                                                                                                                                                                            priceSol:
                                                                                                                                                                                                                      trade.estimatedPriceSol
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                    if (trade.type === "SELL") {
                                                                                                                                                                                                                                          position.sells++;

                                                                                                                                                                                                                                                position.tokensSold +=
                                                                                                                                                                                                                                                        trade.tokenAmount;

                                                                                                                                                                                                                                                              position.solReceived +=
                                                                                                                                                                                                                                                                      trade.solAmount;

                                                                                                                                                                                                                                                                            let remainingToSell =
                                                                                                                                                                                                                                                                                    trade.tokenAmount;

                                                                                                                                                                                                                                                                                          let costOfSoldTokens = 0;

                                                                                                                                                                                                                                                                                                while (
                                                                                                                                                                                                                                                                                                        remainingToSell > 0 &&
                                                                                                                                                                                                                                                                                                                position.lots.length > 0
                                                                                                                                                                                                                                                                                                                      ) {
                                                                                                                                                                                                                                                                                                                              const lot =
                                                                                                                                                                                                                                                                                                                                        position.lots[0];

                                                                                                                                                                                                                                                                                                                                                const tokensFromLot =
                                                                                                                                                                                                                                                                                                                                                          Math.min(
                                                                                                                                                                                                                                                                                                                                                                      remainingToSell,
                                                                                                                                                                                                                                                                                                                                                                                  lot.tokens
                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                    const costPerToken =
                                                                                                                                                                                                                                                                                                                                                                                                              lot.costSol / lot.tokens;

                                                                                                                                                                                                                                                                                                                                                                                                                      const cost =
                                                                                                                                                                                                                                                                                                                                                                                                                                tokensFromLot *
                                                                                                                                                                                                                                                                                                                                                                                                                                          costPerToken;

                                                                                                                                                                                                                                                                                                                                                                                                                                                  costOfSoldTokens += cost;

                                                                                                                                                                                                                                                                                                                                                                                                                                                          lot.tokens -=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tokensFromLot;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lot.costSol -=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cost;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              remainingToSell -=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tokensFromLot;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (lot.tokens <= 0.000000001) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position.lots.shift();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const realizedPnl =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      trade.solAmount -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              costOfSoldTokens;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    position.realizedPnl +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            realizedPnl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (const position of positions.values()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let tokensRemaining = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const lot of position.lots) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tokensRemaining += lot.tokens;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position.tokensRemaining =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tokensRemaining;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    delete position.lots;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return positions;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }