const stamp=v=>{const n=new Date(v||0).getTime();return Number.isFinite(n)?n:0};
export function buildTelemetrySnapshot({jobs=[],states=[],smartScores=[],excluded=new Set(),now=Date.now(),staleMs=300000,workerCapacity=1}){
 const sm=new Map(states.map(s=>[s.wallet_address,s]));
 const rows=jobs.map(job=>{const state=sm.get(job.wallet_address)||{},activity=Math.max(stamp(job.updated_at),stamp(job.started_at),stamp(state.backfill_updated_at),stamp(state.updated_at)),stale=job.status==='running'&&now-activity>staleMs;return {...state,...job,pages_scanned:Number(state.pages_scanned||0),transactions_scanned:state.transactions_scanned??null,history_complete:state.history_complete===true,updated_at:activity?new Date(activity).toISOString():null,telemetryStatus:stale?'stale':job.status,isStale:stale};});
 const summary={running:0,queued:0,complete:0,error:0,paused:0,stale:0,workersConfigured:workerCapacity,workersActive:0};for(const r of rows){if(Object.hasOwn(summary,r.status))summary[r.status]++;if(r.isStale)summary.stale++;}
 const live=rows.filter(r=>r.status==='running'&&!r.isStale).sort((a,b)=>stamp(b.updated_at)-stamp(a.updated_at));summary.workersActive=Math.min(workerCapacity,live.length);
 const included=states.filter(s=>!excluded.has(s.wallet_address)),indexed=included.filter(s=>Number(s.transactions_scanned??Number(s.pages_scanned||0)*100)>0||s.history_complete===true);
 const publicRows=rows.filter(r=>!excluded.has(r.wallet_address));
 const ranked=smartScores.filter(s=>s.eligible===true&&!excluded.has(s.wallet_address)&&sm.get(s.wallet_address)?.history_complete===true).sort((a,b)=>Number(b.score)-Number(a.score));
 const smartWallets=ranked.filter(s=>Number(s.score)>=70).length;
 const smartCalibration={methodology:'smart_score_v1',scoresStored:smartScores.length,eligibleWallets:ranked.length,smartWallets,eliteWallets:ranked.filter(s=>Number(s.score)>=80).length,watchlistWallets:ranked.filter(s=>Number(s.score)>=60&&Number(s.score)<70).length,sampleTarget:100,calibrationProgressPct:Math.min(100,ranked.length),thresholds:{elite:80,smart:70,watchlist:60},status:ranked.length>=100?'ready_for_recalibration':'collecting_sample',note:'Absolute thresholds are provisional until at least 100 eligible complete-history wallets are available.'};
 const indexedAddresses=new Set(indexed.map(s=>s.wallet_address));
 const totalPages=included.reduce((n,s)=>n+Number(s.pages_scanned||0),0),exactTransactions=indexed.every(s=>s.transactions_scanned!=null);
 const network={walletsIndexed:indexed.length,wallets24h:indexed.filter(s=>Math.max(stamp(s.backfill_updated_at),stamp(s.updated_at))>=now-86400000).length,pagesIndexed:totalPages,transactionsIndexed:indexed.reduce((n,s)=>n+Number(s.transactions_scanned||0),0),transactionCounterWallets:indexed.filter(s=>s.transactions_scanned!=null).length,transactionCounterComplete:exactTransactions,completeHistories:indexed.filter(s=>s.history_complete===true).length,indexingNow:publicRows.filter(r=>r.status==='running'&&!r.isStale).length,queued:publicRows.filter(r=>r.status==='queued').length,errors:publicRows.filter(r=>r.status==='error').length,stale:publicRows.filter(r=>r.isStale).length,smartWallets,smartWalletsStatus:smartCalibration.status,updatedAt:new Date(now).toISOString()};
 return {summary,totalPages,pagesPerMinute:null,network,smartCalibration,smartLeaderboard:ranked.slice(0,20).map((s,i)=>({...s,score:Number(s.score),percentile:ranked.length>1?Number((100*(ranked.length-1-i)/(ranked.length-1)).toFixed(1)):100,topPct:Number((100*(i+1)/ranked.length).toFixed(1))})),running:live.slice(0,workerCapacity),jobs:rows.filter(r=>['running','queued','error','paused'].includes(r.status)),latestAnalyses:publicRows.filter(r=>indexedAddresses.has(r.wallet_address)).sort((a,b)=>stamp(b.updated_at)-stamp(a.updated_at)).slice(0,10)};
}
export function publicTelemetry(snapshot){const n=snapshot.network;return {network:n,totalPages:n.pagesIndexed,pagesPerMinute:snapshot.pagesPerMinute,summary:{workersConfigured:snapshot.summary.workersConfigured,workersActive:Math.min(snapshot.summary.workersConfigured,n.indexingNow),queued:n.queued,error:n.errors,stale:n.stale},latestAnalyses:snapshot.latestAnalyses.map(r=>({wallet_address:r.wallet_address,status:r.status,telemetryStatus:r.telemetryStatus,pages_scanned:r.pages_scanned,transactions_scanned:r.transactions_scanned,history_complete:r.history_complete,updated_at:r.updated_at}))};}
