import { getAnalysisCache, getSyncState } from "./db.js";
import { isCurrentAnalysis } from "./analysisRevision.js";
import { assertWalletReadable } from "./walletPolicy.js";
import { analyzeWallet } from "./walletAnalyzer.js";
const BASE=String(process.env.SUPABASE_URL||"").replace(/\/$/,"");const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;const MIN_COST=Number(process.env.MIN_RANKED_TRADE_COST_SOL||.005);let run=null;
async function rest(path){const r=await fetch(`${BASE}/rest/v1/${path}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
export function getTradeJourneyBackfillStatus(){return run||{status:"idle"}}
export function startTradeJourneyBackfill(){if(run?.status==="running")return run;run={status:"running",startedAt:new Date().toISOString(),walletsTotal:0,walletsDone:0,journeysWritten:0,failures:[],currentWallet:null};void(async()=>{try{const states=await rest("wallet_sync_state?select=wallet_address&history_complete=eq.true&order=wallet_address.asc");run.walletsTotal=states.length;for(const {wallet_address:wallet} of states){run.currentWallet=wallet;try{await assertWalletReadable(wallet);const [cache,state]=await Promise.all([getAnalysisCache(wallet),getSyncState(wallet)]);if(isCurrentAnalysis(cache,state)){run.walletsDone++;continue}const result=await analyzeWallet(wallet,{mode:"deep",readOnly:true});run.journeysWritten+=result.metrics.intelligenceSnapshot.journeys.count;run.walletsDone++}catch(e){run.failures.push({wallet,error:String(e?.message||e)});run.walletsDone++}}run.status=run.failures.length?"completed_with_errors":"complete";run.currentWallet=null;run.finishedAt=new Date().toISOString()}catch(e){run.status="failed";run.error=String(e?.message||e);run.currentWallet=null;run.finishedAt=new Date().toISOString()}})();return run}

