import { requestWalletDashboard } from "./walletProductService.js";
import { getWalletTradePage, getWalletTransferPage, getWalletRewardsPage } from "./db.js";
import { buildPositions, isLowConfidenceDustTrade } from "./positionEngine.js";
import { buildTradeJourneys } from "./tradeJourneyEngine.js";
import { buildHoldBehavior } from "./holdIntelligence.js";
import { buildWalletIntelligenceSummary } from "./intelligenceSummary.js";
import { buildCreatorRevenueIntelligence } from "./creatorRevenueService.js";
import { getWalletPortfolioSnapshot, applyPortfolioPricesToDashboard } from "./walletPortfolioService.js";
import { getTokenMetadata } from "./helius.js";
function mapTrade(row){return{wallet:row.wallet_address,signature:row.signature,slot:row.slot==null?null:Number(row.slot),eventIndex:Number(row.event_index||0),blockTime:row.block_time?Math.floor(new Date(row.block_time).getTime()/1000):null,type:row.type,tokenMint:row.token_mint,tokenAmount:Number(row.token_amount),solAmount:Number(row.sol_amount),estimatedPriceSol:row.estimated_price_sol==null?null:Number(row.estimated_price_sol),feeSol:row.fee_sol==null?null:Number(row.fee_sol),dex:row.dex,parser:row.parser}}
function mapTransfer(row){return{wallet:row.wallet_address,signature:row.signature,slot:row.slot==null?null:Number(row.slot),eventIndex:Number(row.event_index||0),blockTime:row.block_time?Math.floor(new Date(row.block_time).getTime()/1000):null,direction:row.direction,mint:row.token_mint,amount:Number(row.token_amount),sourceAddress:row.source_address,destinationAddress:row.destination_address,parser:row.parser}}
function mapReward(row){return{wallet:row.wallet_address,signature:row.signature,slot:row.slot==null?null:Number(row.slot),blockTime:row.block_time?Math.floor(new Date(row.block_time).getTime()/1000):null,rewardType:row.reward_type,quoteMint:row.quote_mint,amount:Number(row.amount),creator:row.creator,instructionIndex:Number(row.instruction_index)}}
async function readAll(pageFn,address,mapper,maxRows){const rows=[],pageSize=1000;for(let offset=0;offset<maxRows;offset+=pageSize){const page=await pageFn(address,pageSize,offset);if(!page.length)break;rows.push(...page.map(mapper));if(page.length<pageSize)break}return rows}
async function journeyRows(wallet,trades){const rows=buildTradeJourneys(trades).filter(j=>j.closed&&j.realizedCost>=Number(process.env.MIN_RANKED_TRADE_COST_SOL||.005)&&Number.isFinite(j.pnlPct));rows.sort((a,b)=>b.realizedPnl-a.realizedPnl);const picked=[...rows.slice(0,6),...rows.slice(-6)].filter((v,i,a)=>a.indexOf(v)===i);const metas=new Map(await Promise.all([...new Set(picked.map(j=>j.tokenMint))].map(async mint=>{try{return[mint,await getTokenMetadata(mint)]}catch{return[mint,null]}})));const shape=j=>{const m=metas.get(j.tokenMint);return{wallet,journeyId:j.id,tokenMint:j.tokenMint,tokenName:m?.name||null,tokenSymbol:m?.symbol||null,tokenImage:`/api/token-image/${encodeURIComponent(j.tokenMint)}`,costSol:j.realizedCost,proceedsSol:j.realizedCost+j.realizedPnl,pnlSol:j.realizedPnl,roiPct:j.pnlPct,holdSeconds:j.holdSeconds,hold:j.hold,entryTime:j.entryTime,exitTime:j.exitTime,detailUrl:`/data/trade/${encodeURIComponent(wallet)}/${encodeURIComponent(j.tokenMint)}?journey=${encodeURIComponent(j.id)}`}};return{best:rows.filter(j=>j.realizedPnl>0).slice(0,6).map(shape),worst:[...rows].filter(j=>j.realizedPnl<0).sort((a,b)=>a.realizedPnl-b.realizedPnl).slice(0,6).map(shape),count:rows.length}}
async function buildBehavioralIntelligence(address,historyComplete){const maxRows=Number(process.env.MAX_DEEP_TRADE_ROWS||500000);const[tradesRaw,transfers,rewards]=await Promise.all([readAll(getWalletTradePage,address,mapTrade,maxRows),readAll(getWalletTransferPage,address,mapTransfer,maxRows),readAll(getWalletRewardsPage,address,mapReward,maxRows)]);const trades=tradesRaw.filter(trade=>!isLowConfidenceDustTrade(trade));const positions=[...buildPositions(trades,transfers,rewards).values()],holdBehavior=buildHoldBehavior(positions),providerReady=Boolean(process.env.BIRDEYE_API_KEY),summary=buildWalletIntelligenceSummary(positions,holdBehavior,{historyComplete}),journeys=await journeyRows(address,trades);return{holdBehavior:{...holdBehavior,status:historyComplete?"ready":"provisional",marketJourney:{status:providerReady?"provider_ready":"provider_pending",provider:"birdeye"}},intelligence:{...summary,marketIntelligence:{status:providerReady?"provider_configured":"provider_pending",provider:"birdeye",features:["TRADE_JOURNEY","MFE_MAE","MISSED_MILLIONS","DIAMOND_HANDS","ELITE_EXITS"]}},journeys}}
function pendingIntelligence(){return{methodology:"explainable_behavior_summary_v1",status:"pending_history",confidence:"pending",strengths:[],weaknesses:[],observations:[],risk:{},marketIntelligence:{status:process.env.BIRDEYE_API_KEY?"provider_configured":"provider_pending",provider:"birdeye"}}}
function attachLazyPanels(dashboard,address){dashboard.creatorRevenue={status:"loading",wallet:address,source:"pump_fun_public_api",topCoins:[]};dashboard.incoming={status:"loading",wallet:address,minUsd:Number(process.env.MIN_INCOMING_USD||5),highestValue:[],latest:[],events:[]};return dashboard}
export async function requestCreatorRevenue(address){return buildCreatorRevenueIntelligence(address)}
export async function requestWalletDashboardWithIntelligence(address,options={}){const[dashboard,portfolioResult]=await Promise.all([requestWalletDashboard(address,options),getWalletPortfolioSnapshot(address).catch(error=>({status:"unavailable",error:error.message}))]);applyPortfolioPricesToDashboard(dashboard,portfolioResult);if(!dashboard.portfolio)dashboard.portfolio=portfolioResult;attachLazyPanels(dashboard,address);const historyComplete=dashboard?.coverage?.historyComplete===true;if(!historyComplete){dashboard.behavior=dashboard.behavior||{status:"pending_history",sampleSize:0,behaviorTags:[],longest:[],shortest:[]};dashboard.intelligence=pendingIntelligence();dashboard.responseMode="fast_snapshot";return dashboard}try{const extra=await buildBehavioralIntelligence(address,true);if(!dashboard.behavior||dashboard.behavior.status==="unavailable")dashboard.behavior=extra.holdBehavior;dashboard.intelligence=extra.intelligence;dashboard.trades={...(dashboard.trades||{}),best:extra.journeys.best,worst:extra.journeys.worst,rankingUnit:"TRADE_JOURNEY",journeysAnalyzed:extra.journeys.count}}catch(error){console.warn(`Unable to build behavioral intelligence for ${address}: ${error?.message||error}`);dashboard.intelligence={...pendingIntelligence(),confidence:"unavailable",status:"unavailable",observations:["Behavioral intelligence is temporarily unavailable."]}}dashboard.responseMode="cached_deep";return dashboard}
