import { isCurrentAnalysis, analysisRevision } from "./analysisRevision.js";
import { createResultCache } from "./resultCache.js";
import { getWalletPortfolioSnapshot } from "./walletPortfolioService.js";
const analysisRequests = createResultCache({ttlMs: 1000, maxEntries: 100});
import { assertWalletReadable, policyError, publicAnalysisPolicy } from "./walletPolicy.js";
import { transactionAllowance } from "./analysisBudget.js";
import { analyzeWallet } from "./walletAnalyzer.js";
import { getAnalysisCache, getSyncState } from "./db.js";
import { enqueueWalletIndexJob } from "./indexQueue.js";
import { buildWalletDashboardResponse } from "./walletDashboardContract.js";
import { getTokenMetadata } from "./helius.js";
import { buildClusterIntelligence } from "./clusterEngine.js";
import { buildWalletHoldBehavior } from "./walletBehaviorService.js";

const WSOL_MINT="So11111111111111111111111111111111111111112",clusterCache=createResultCache({ttlMs:Number(process.env.CLUSTER_CACHE_MS||60000),maxEntries:100}),behaviorCache=new Map(),CLUSTER_CACHE_MS=Number(process.env.CLUSTER_CACHE_MS||60000),BEHAVIOR_CACHE_MS=Number(process.env.BEHAVIOR_CACHE_MS||300000),INDEX_ACTIVE_WINDOW_MS=Number(process.env.INDEX_ACTIVE_WINDOW_MS||90000),MIN_INCOMING_USD=Number(process.env.MIN_INCOMING_USD||5),MIN_RANKED_TRADE_COST_SOL=Number(process.env.MIN_RANKED_TRADE_COST_SOL||.005),DASHBOARD_SAMPLE_SIZE=6,METADATA_CONCURRENCY=Math.max(1,Number(process.env.TOKEN_METADATA_CONCURRENCY||4));
function coverageFromState(state){const historyComplete=state?.history_complete===true,progressAt=state?.backfill_updated_at||state?.last_synced_at||null,progressMs=progressAt?new Date(progressAt).getTime():0,progressAgeMs=progressMs>0?Date.now()-progressMs:null,active=!historyComplete&&state?.status==="syncing"&&progressAgeMs!=null&&progressAgeMs<=INDEX_ACTIVE_WINDOW_MS,stalled=!historyComplete&&state?.status==="syncing"&&progressAgeMs!=null&&progressAgeMs>INDEX_ACTIVE_WINDOW_MS;return{status:historyComplete?"complete":active?"active":stalled?"stalled":"queued",historyComplete,active,stalled,backfillPending:!historyComplete&&Boolean(state?.backfill_pagination_token),pagesScanned:Number(state?.pages_scanned||0),oldestIndexedAt:state?.oldest_block_time||null,newestIndexedAt:state?.newest_block_time||null,lastSyncedAt:state?.last_synced_at||null,backfillUpdatedAt:state?.backfill_updated_at||null,progressAgeMs}}
function sanitizeMetrics(metrics){if(!metrics||typeof metrics!=="object")return metrics;const tokenNetRanking=["TOKEN_LIFETIME_NET","CLOSED_TOKEN_LIFETIME_NET"].includes(metrics.rankingUnit),cleanRanked=items=>(Array.isArray(items)?items:[]).filter(result=>(tokenNetRanking||result?.pnlComplete===true)&&Number.isFinite(Number(result?.costSol))&&Number(result.costSol)>=MIN_RANKED_TRADE_COST_SOL&&Number.isFinite(Number(result?.roiPct))),originalBest=Array.isArray(metrics.bestTrades)?metrics.bestTrades.length:0,originalWorst=Array.isArray(metrics.worstTrades)?metrics.worstTrades.length:0,bestTrades=cleanRanked(metrics.bestTrades).filter(r=>Number(r.pnlSol)>0).slice(0,DASHBOARD_SAMPLE_SIZE),worstTrades=cleanRanked(metrics.worstTrades).filter(r=>Number(r.pnlSol)<0).slice(0,DASHBOARD_SAMPLE_SIZE);return{...metrics,bestTrades,worstTrades,topPositions:(Array.isArray(metrics.topPositions)?metrics.topPositions:[]).slice(0,DASHBOARD_SAMPLE_SIZE),rankingMinCostSol:Number(metrics.rankingMinCostSol||MIN_RANKED_TRADE_COST_SOL),rankingTradesExcluded:Number(metrics.rankingTradesExcluded||0)+(originalBest-bestTrades.length)+(originalWorst-worstTrades.length),rankedRealizedTradesAnalyzed:Number(metrics.rankedRealizedTradesAnalyzed||metrics.realizedTradesAnalyzed||0)}}
function mintForEntity(entity){if(entity?.tokenMint)return entity.tokenMint;if(entity?.assetType==="SOL")return WSOL_MINT;if(entity?.assetType==="TOKEN")return entity.assetId||null;return null}
async function mapWithConcurrency(items,limit,worker){const output=new Array(items.length);let cursor=0;async function run(){while(true){const index=cursor++;if(index>=items.length)return;output[index]=await worker(items[index],index)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return output}
async function enrichTokenMetadata(dashboard){const behavior=dashboard?.behavior||{},entities=[...(dashboard?.positions?.top||[]),dashboard?.positions?.best,dashboard?.positions?.worst,...(dashboard?.trades?.best||[]),...(dashboard?.trades?.worst||[]),...(dashboard?.externalTokens?.topSales||[]),...(dashboard?.funding?.events||[]),...(dashboard?.rewards?.events||[]),...(behavior?.longest||[]),...(behavior?.shortest||[])].filter(Boolean),mints=[...new Set(entities.map(mintForEntity).filter(Boolean))],metadataEntries=await mapWithConcurrency(mints,METADATA_CONCURRENCY,async mint=>{try{return[mint,await getTokenMetadata(mint)]}catch(error){console.warn(`Unable to load metadata for ${mint}: ${error.message}`);return[mint,null]}}),metadataByMint=new Map(metadataEntries);for(const entity of entities){const mint=mintForEntity(entity);if(!mint)continue;const metadata=metadataByMint.get(mint);entity.tokenName=entity.assetType==="SOL"?"Solana":metadata?.name||null;entity.tokenSymbol=entity.assetType==="SOL"?"SOL":metadata?.symbol||null;entity.tokenImage=`/api/token-image/${encodeURIComponent(mint)}`;entity.tokenImageSource=metadata?.imageSource||"proxy_fallback";entity.priceUsd=Number.isFinite(Number(metadata?.priceUsd))?Number(metadata.priceUsd):null;entity.estimatedUsd=entity.priceUsd!=null&&Number.isFinite(Number(entity.amount))?Number(entity.amount)*entity.priceUsd:null}return dashboard}
async function buildLivePortfolio(address){try{const portfolio=await getWalletPortfolioSnapshot(address),snapshot={holdings:portfolio.holdings,nativeBalanceLamports:portfolio.solBalance*1e9},sorted=[...snapshot.holdings].sort((a,b)=>(Number(b.valueUsd)||0)-(Number(a.valueUsd)||0)||Number(b.amount)-Number(a.amount)).slice(0,50),enriched=await mapWithConcurrency(sorted,METADATA_CONCURRENCY,async item=>{let meta=null;try{if(!item.tokenName||!item.tokenSymbol||item.priceUsd==null)meta=await getTokenMetadata(item.tokenMint)}catch{}const priceUsd=item.priceUsd??meta?.priceUsd??null;return{...item,tokenName:item.tokenName||item.name||meta?.name||null,tokenSymbol:item.tokenSymbol||item.symbol||meta?.symbol||null,tokenImage:`/api/token-image/${encodeURIComponent(item.tokenMint)}`,priceUsd,valueUsd:priceUsd!=null?item.amount*priceUsd:item.valueUsd}});return{status:"ready",source:"current_chain_state",updatedAt:new Date().toISOString(),count:snapshot.holdings.length,nativeSol:Number(snapshot.nativeBalanceLamports||0)/1e9,positions:enriched}}catch(error){console.warn(`Unable to load live portfolio for ${address}: ${error.message}`);return{status:"unavailable",source:"current_chain_state",updatedAt:new Date().toISOString(),count:0,nativeSol:null,positions:[]}}}
function aggregateCreatorFeeClaims(events){const grouped=new Map();for(const event of events){const payoutMint=event?.tokenMint||event?.assetId;if(!payoutMint)continue;const previous=grouped.get(payoutMint),amount=Number(event?.amount||0),estimatedUsd=Number(event?.estimatedUsd),blockTime=Number(event?.blockTime||0);if(!previous){grouped.set(payoutMint,{...event,assetType:"TOKEN",assetId:payoutMint,tokenMint:payoutMint,payoutMint,classification:"CREATOR_REWARD",eventType:"CREATOR_FEE_CLAIM",amount,estimatedUsd:Number.isFinite(estimatedUsd)?estimatedUsd:null,claimCount:1,firstBlockTime:blockTime||null,lastBlockTime:blockTime||null,blockTime:blockTime||null,signature:event?.signature||null});continue}previous.amount+=amount;previous.claimCount+=1;if(Number.isFinite(estimatedUsd))previous.estimatedUsd=Number(previous.estimatedUsd||0)+estimatedUsd;if(blockTime&&(!previous.firstBlockTime||blockTime<previous.firstBlockTime))previous.firstBlockTime=blockTime;if(blockTime&&(!previous.lastBlockTime||blockTime>previous.lastBlockTime)){previous.lastBlockTime=blockTime;previous.blockTime=blockTime;previous.signature=event?.signature||previous.signature}}return[...grouped.values()]}
function filterMeaningfulIncoming(dashboard){const funding=dashboard?.funding||{},rewards=dashboard?.rewards||{},rawFunding=Array.isArray(funding.events)?funding.events:[],rawRewards=Array.isArray(rewards.events)?rewards.events:[],aggregatedClaims=aggregateCreatorFeeClaims(rawRewards),keep=event=>Number.isFinite(Number(event?.estimatedUsd))&&Number(event.estimatedUsd)>=MIN_INCOMING_USD,visibleFunding=rawFunding.filter(keep),visibleClaimGroups=aggregatedClaims.filter(keep),totalEstimatedUsd=visibleClaimGroups.reduce((s,e)=>s+Number(e.estimatedUsd||0),0),visibleClaimCount=visibleClaimGroups.reduce((s,e)=>s+Number(e.claimCount||0),0),visibleAll=[...visibleFunding,...visibleClaimGroups],highestValue=[...visibleAll].sort((a,b)=>Number(b.estimatedUsd||0)-Number(a.estimatedUsd||0)||Number(b.blockTime||0)-Number(a.blockTime||0)).slice(0,30),latest=[...visibleAll].sort((a,b)=>Number(b.blockTime||0)-Number(a.blockTime||0)||Number(b.estimatedUsd||0)-Number(a.estimatedUsd||0)).slice(0,30);funding.rawCount=rawFunding.length;funding.count=visibleFunding.length;funding.events=visibleFunding;funding.hiddenBelowThresholdOrUnpriced=rawFunding.length-visibleFunding.length;funding.minUsd=MIN_INCOMING_USD;funding.solTotal=visibleFunding.filter(e=>e.assetType==="SOL").reduce((s,e)=>s+Number(e.amount||0),0);rewards.aggregatedClaims=aggregatedClaims;rewards.visibleAggregatedClaims=visibleClaimGroups;rewards.hiddenBelowThresholdOrUnpriced=aggregatedClaims.length-visibleClaimGroups.length;rewards.minUsd=MIN_INCOMING_USD;rewards.summary={claimCount:rawRewards.length,visibleClaimCount,payoutAssetCount:aggregatedClaims.length,visiblePayoutAssetCount:visibleClaimGroups.length,estimatedUsdTotal:totalEstimatedUsd,attribution:"payout_asset",sourceTokenAttributionAvailable:false};dashboard.incoming={minUsd:MIN_INCOMING_USD,defaultSort:"highest_value",events:highestValue,highestValue,latest,transferCount:visibleFunding.length,rewardCount:visibleClaimGroups.length,rewardClaimCount:visibleClaimCount,hiddenBelowThresholdOrUnpriced:funding.hiddenBelowThresholdOrUnpriced+rewards.hiddenBelowThresholdOrUnpriced};return dashboard}
async function clusterForWallet(address,revision){try{return await clusterCache.get(`${address}:${revision}`,()=>buildClusterIntelligence(address))}catch{return{methodology:"relationship_score_v1",status:"unavailable",candidateWallets:0,analyzedCandidateWallets:0,likelyRelatedWallets:0,strongestScore:0,members:[],relationships:[]}}}
function pendingCluster(){return{methodology:"relationship_score_v1",status:"pending_history",candidateWallets:0,analyzedCandidateWallets:0,likelyRelatedWallets:0,strongestScore:0,members:[],relationships:[]}}function pendingBehavior(){return{status:"pending_history",sampleSize:0,behaviorTags:[],longest:[],shortest:[],marketJourney:{status:process.env.BIRDEYE_API_KEY?"provider_ready":"awaiting_birdeye",provider:"birdeye"}}}async function behaviorForWallet(address,historyComplete){if(!historyComplete)return pendingBehavior();const cached=behaviorCache.get(address);if(cached&&Date.now()-cached.createdAt<BEHAVIOR_CACHE_MS)return cached.value;try{const behavior=await buildWalletHoldBehavior(address),value={status:"ready",...behavior};behaviorCache.set(address,{createdAt:Date.now(),value});return value}catch{return{...pendingBehavior(),status:"unavailable"}}}
async function loadMetricsForRequest(address,stateBefore,policy){
  const cached=await getAnalysisCache(address);
  if(isCurrentAnalysis(cached,stateBefore))return sanitizeMetrics(cached.metrics);
  if(policyError(policy)){
    if(!stateBefore){const error=policyError(policy);throw error}
    return sanitizeMetrics((await analyzeWallet(address,{mode:"quick",readOnly:true})).metrics);
  }
  if(stateBefore?.history_complete===true || (stateBefore && !transactionAllowance(stateBefore,policy)))
    return sanitizeMetrics((await analyzeWallet(address,{mode:"quick",readOnly:true})).metrics);
  try{return sanitizeMetrics((await analyzeWallet(address,{mode:"quick"})).metrics)}catch(error){
    if(!String(error?.message||"").includes("already in progress"))throw error;
    const cached=await getAnalysisCache(address);if(isCurrentAnalysis(cached,stateBefore))return sanitizeMetrics(cached.metrics);throw error;
  }
}
async function metricsForRequest(address,state,policy){return analysisRequests.get(`${address}:${analysisRevision(state)}`,()=>loadMetricsForRequest(address,state,policy))}
export async function requestWalletIntelligence(address,options={}){
  const policy=await assertWalletReadable(address),priority=100,stateBefore=await getSyncState(address),metrics=await metricsForRequest(address,stateBefore,policy),state=await getSyncState(address),coverage=coverageFromState(state);
  coverage.budgetExhausted=!coverage.historyComplete&&!transactionAllowance(state,policy);
  coverage.indexingRestricted=Boolean(policyError(policy));
  if(!coverage.historyComplete){if(coverage.indexingRestricted)coverage.status="blocked";else if(coverage.budgetExhausted)coverage.status="paused"}
  let indexJob=null;
  if(!coverage.historyComplete&&!coverage.budgetExhausted&&!coverage.indexingRestricted)indexJob=await enqueueWalletIndexJob(address,priority);
  return{wallet:address,status:coverage.historyComplete?"ready":coverage.indexingRestricted?"restricted":coverage.budgetExhausted?"paused":"indexing",analysisPolicy:publicAnalysisPolicy(policy),metricsStatus:coverage.historyComplete&&metrics.metricsComplete===true?"final":"partial",coverage,metrics,indexJob:indexJob?{status:indexJob.status,priority:indexJob.priority,attempts:indexJob.attempts,requestedAt:indexJob.requested_at,updatedAt:indexJob.updated_at}:null};
}
export async function requestWalletDashboard(address,options={}){const policy=await assertWalletReadable(address);const[result,livePortfolio]=await Promise.all([requestWalletIntelligence(address,options),buildLivePortfolio(address)]),dashboard=buildWalletDashboardResponse(result),historyComplete=result.coverage.historyComplete===true,clusterPromise=historyComplete?clusterForWallet(address,result.metrics.sourceRevision):Promise.resolve(pendingCluster()),behaviorPromise=result.metrics?.intelligenceSnapshot?.holdBehavior?Promise.resolve(result.metrics.intelligenceSnapshot.holdBehavior):behaviorForWallet(address,historyComplete),[cluster,behavior]=await Promise.all([clusterPromise,behaviorPromise]);dashboard.analysisPolicy=publicAnalysisPolicy(policy);dashboard.cluster=cluster;dashboard.behavior=behavior;dashboard.livePortfolio=livePortfolio;const enriched=await enrichTokenMetadata(dashboard);filterMeaningfulIncoming(enriched);return enriched}
if(process.argv[1]?.endsWith("walletProductService.js")){const address=process.argv[2];if(!address){console.error("Usage: npm run product:wallet -- <wallet>");process.exit(1)}try{console.log(JSON.stringify(await requestWalletDashboard(address),null,2))}catch(error){console.error("Wallet product request failed:",error.message);process.exit(1)}}

